#!/bin/bash

IFS=,
BATTERY_INFO=($(acpi | awk -F'[ ,%]' '$5 > 0 || $6 > 0 {print $0}'))
BATTERY_CAPACITY=${BATTERY_INFO[1]# }
WARN_FLAG=0
CAPACITY=30

case "${BATTERY_INFO[0]#*: }" in
    "Charging")
        echo "${BATTERY_CAPACITY}"
        ;;
    "Not charging")
        echo "${BATTERY_CAPACITY}"
        ;;
    "Discharging")
        WARN_FLAG=1
        case $[${BATTERY_CAPACITY%\%}/10] in
            [0-1])
                echo "󰀙${BATTERY_CAPACITY}"
                ;;
            [2-4])
                echo "󰀘${BATTERY_CAPACITY}"
                ;;
            [5-6])
                echo "󰀗${BATTERY_CAPACITY}"
                ;;
            [7-8])
                echo "󰀖${BATTERY_CAPACITY}"
                ;;
            9|10)
                echo "󰀕${BATTERY_CAPACITY}"
                ;;
        esac
        ;;
esac

if [ ${BATTERY_CAPACITY%\%} -le ${CAPACITY} ]  && [ $WARN_FLAG -eq 1 ]; then
    xautolock -notify 30\
              -notifier "[[ \$(acpi -a) =~ \"off-line\" ]] && [ \$(acpi | awk -F',' '{gsub(/ |%/,\"\"); print \$2}') -le 30 ] && notify-send -u critical -t 10000 \"Low battery ${BATTERY_CAPACITY}\" \"System is going to sleep.\" || xautolock -exit" \
              -time 1\
              -locker "xautolock -exit; i3lock; systemctl suspend" &
    exit 33
fi

case ${BLOCK_BUTTON} in
    1) rofi -e "$(acpi -V)" ;;
    *) : ;;
esac
